### ISSUE TITLE
datahub start problem/ the login page have nothing only some information

### ISSUE THREAD

**Issue by looperEit** [datahub-project/datahub#4849] opened 2022-05-06 07:36 UTC
when i start the datahub, the login page didn't perform well.
![image](https://user-images.githubusercontent.com/46367388/167087916-bc1e9e0a-584a-4943-a53b-cb1fb8d2a17b.png)\

and the docker status like this:

![image](https://user-images.githubusercontent.com/46367388/167088004-80846702-b2e6-4c43-ae7b-9c18b4e6b071.png)

**Comment by xiphl** [comment] 2022-05-06 07:52
if gms is not healthy, login will not work correctly. but why are you showing port:9200 instead of 9002 to show that login is wonky?

**Comment by looperEit** [comment] 2022-05-06 08:07
> if gms is not healthy, login will not work correctly. but why are you showing port:9200 instead of 9002 to show that login is wonky?
oh sorry.... i’m so sorry i got the login page but i still facing the problem,which i guess that is the gms problem.
![image](https://user-images.githubusercontent.com/46367388/167091312-c48fb694-b336-4c7a-ae2a-0608850a2dab.png)

could you tell me how to fix it？

by the way, my partner used the older version, instead of the latest. He did't have this problem. 
is this a "version-problem"？

i used the 0.8.34.1
![image](https://user-images.githubusercontent.com/46367388/167092692-97bd7a0c-c467-4dd5-9be2-5e7042d25831.png)

he used the 0.8.24

**Comment by RyanHolstien** [comment] 2022-05-10 23:22
Do you have the GMS start up logs? This error is what you will see on the frontend if GMS is not running and based on your previous image I'm guessing GMS is still showing unhealthy?

**Comment by looperEit** [comment] 2022-05-11 02:03
> Do you have the GMS start up logs? This error is what you will see on the frontend if GMS is not running and based on your previous image I'm guessing GMS is still showing unhealthy?

thanks for your replying, there is the logs:
![image](https://user-images.githubusercontent.com/46367388/167753989-1e589c13-18bd-44ad-978b-215a10655965.png)

**Comment by looperEit** [comment] 2022-05-11 02:05
> Do you have the GMS start up logs? This error is what you will see on the frontend if GMS is not running and based on your previous image I'm guessing GMS is still showing unhealthy?

> b/datahub-gms/scripts/jetty.xml /datahub/datahub-gms/bin/war.war
2022/05/06 14:31:20 Waiting for: http://elasticsearch:9200/
2022/05/06 14:31:20 Waiting for: tcp://mysql:3306
2022/05/06 14:31:20 Waiting for: tcp://broker:29092
2022/05/06 14:31:20 Connected to tcp://mysql:3306
2022/05/06 14:31:20 Problem with dial: dial tcp 172.18.0.6:29092: connect: connection refused. Sleeping 1s
2022/05/06 14:31:20 Received 200 from http://elasticsearch:9200/
2022/05/06 14:31:21 Problem with dial: dial tcp 172.18.0.6:29092: connect: connection refused. Sleeping 1s
2022/05/06 14:31:22 Problem with dial: dial tcp 172.18.0.6:29092: connect: connection refused. Sleeping 1s
2022/05/06 14:31:23 Connected to tcp://broker:29092
2022-05-06 14:31:24.165:INFO::main: Logging initialized @597ms to org.eclipse.jetty.util.log.StdErrLog
WARNING: jetty-runner is deprecated.
See Jetty Documentation for startup options
https://www.eclipse.org/jetty/documentation/
2022-05-06 14:31:24.228:INFO:oejr.Runner:main: Runner
2022-05-06 14:31:24.448:INFO:oeju.TypeUtil:main: JVM Runtime does not support Modules
2022-05-06 14:31:24.599:INFO:oejs.Server:main: jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_302-b08
2022-05-06 14:31:25.181:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@50cbc42f{/,null,UNAVAILABLE}{file:///datahub/datahub-gms/bin/war.war}
java.util.zip.ZipException: invalid entry CRC (expected 0xe78b2198 but got 0xde56297a)
at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:394)
at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
at java.util.jar.JarInputStream.read(JarInputStream.java:207)
at org.eclipse.jetty.util.IO.copy(IO.java:172)
at org.eclipse.jetty.util.IO.copy(IO.java:122)
at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:218)
at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:636)
at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:140)
at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.server.Server.start(Server.java:407)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
at org.eclipse.jetty.server.Server.doStart(Server.java:371)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
2022-05-06 14:31:25.219:INFO:oejs.AbstractConnector:main: Started ServerConnector@39a054a5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2022-05-06 14:31:25.220:INFO:oejs.Server:main: Started @1659ms

**Comment by RyanHolstien** [comment] 2022-05-11 18:56
This appears to be a duplicate of the other two issues that you have opened and of: https://github.com/datahub-project/datahub/issues/4690#issuecomment-1104012823 where Pedro has done some digging into the issue. Please do not open many issues for the same problem 😄

**Closed by RyanHolstien** 2022-05-11 18:56 UTC
Labels: bug
