### ISSUE TITLE
datahub-rest : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in

### ISSUE THREAD

**Issue by zed-intelliflo** [datahub-project/datahub#6330] opened 2022-11-01 17:23 UTC
**Describe the bug**
Getting this error for publicly signed certificate 

**To Reproduce**

**Expected behavior**
Cert should be seen as valid
or would be great if can be overridden 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': '76c822f0-99dd-45d3-8937-11414b0e1072',
 'infos': ['2022-11-01 17:17:13.392846 [exec_id=76c822f0-99dd-45d3-8937-11414b0e1072] INFO: Starting execution for task with name=RUN_INGEST',
           '2022-11-01 17:17:17.441601 [exec_id=76c822f0-99dd-45d3-8937-11414b0e1072] INFO: stdout=venv setup time = 0\n'
           'This version of datahub supports report-to functionality\n'
           'datahub  ingest run -c /tmp/datahub/ingest/76c822f0-99dd-45d3-8937-11414b0e1072/recipe.yml --report-to '
           '/tmp/datahub/ingest/76c822f0-99dd-45d3-8937-11414b0e1072/ingestion_report.json\n'
           '[2022-11-01 17:17:15,251] INFO     {datahub.cli.ingest_cli:182} - DataHub CLI version: 0.9.0\n'
           '[2022-11-01 17:17:15,271] INFO     {datahub.ingestion.run.pipeline:175} - Sink configured successfully. DataHubRestEmitter: configured '
           'to talk to http://datahub-gms:8080\n'
           '[2022-11-01 17:17:15,273] INFO     {datahub.ingestion.run.pipeline:200} - Source configured successfully.\n'
           '[2022-11-01 17:17:15,274] INFO     {datahub.cli.ingest_cli:129} - Starting metadata ingestion\n'
           '[2022-11-01 17:17:15,410] INFO     {datahub.ingestion.reporting.file_reporter:54} - Wrote UNKNOWN report successfully to '
           "<_io.TextIOWrapper name='/tmp/datahub/ingest/76c822f0-99dd-45d3-8937-11414b0e1072/ingestion_report.json' mode='w' encoding='UTF-8'>\n"
           '[2022-11-01 17:17:15,411] INFO     {datahub.cli.ingest_cli:136} - Source (openapi) report:\n'
           "{'events_produced': '0',\n"
           " 'events_produced_per_sec': '0',\n"
           " 'event_ids': [],\n"
           " 'warnings': {},\n"
           " 'failures': {},\n"
           " 'start_time': '2022-11-01 17:17:15.273730 (now).',\n"
           " 'running_time': '0.14 seconds'}\n"
           '[2022-11-01 17:17:15,411] INFO     {datahub.cli.ingest_cli:139} - Sink (datahub-rest) report:\n'
           "{'total_records_written': '0',\n"
           " 'records_written_per_second': '0',\n"
           " 'warnings': [],\n"
           " 'failures': [],\n"
           " 'start_time': '2022-11-01 17:17:15.268643 (now).',\n"
           " 'current_time': '2022-11-01 17:17:15.411211 (now).',\n"
           " 'total_duration_in_seconds': '0.14',\n"
           " 'gms_version': 'v0.9.0',\n"
           " 'pending_requests': '0'}\n"
           '[2022-11-01 17:17:15,852] ERROR    {datahub.entrypoints:192} - \n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen\n'
           '    httplib_response = self._make_request(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request\n'
           '    self._validate_conn(conn)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn\n'
           '    conn.connect()\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect\n'
           '    self.sock = ssl_wrap_socket(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket\n'
           '    ssl_sock = _ssl_wrap_socket_impl(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl\n'
           '    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)\n'
           '  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket\n'
           '    return self.sslsocket_class._create(\n'
           '  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create\n'
           '    self.do_handshake()\n'
           '  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake\n'
           '    self._sslobj.do_handshake()\n'
           'ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain '
           '(_ssl.c:997)\n'
           '\n'
           'During handling of the above exception, another exception occurred:\n'
           '\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/adapters.py", line 489, in send\n'
           '    resp = conn.urlopen(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen\n'
           '    retries = retries.increment(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment\n'
           '    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n'
           "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='*', port=443): Max retries "
           "exceeded with url: /docs/v2/swagger (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify "
           "failed: self signed certificate in certificate chain (_ssl.c:997)')))\n"
           '\n'
           'During handling of the above exception, another exception occurred:\n'
           '\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/entrypoints.py", line 149, in main\n'
           '    sys.exit(datahub(standalone_mode=False, **kwargs))\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__\n'
           '    return self.main(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/click/core.py", line 1055, in main\n'
           '    rv = self.invoke(ctx)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke\n'
           '    return ctx.invoke(self.callback, **ctx.params)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke\n'
           '    return __callback(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func\n'
           '    return f(get_current_context(), *args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 347, in wrapper\n'
           '    raise e\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 299, in wrapper\n'
           '    res = func(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/utilities/memory_leak_detector.py", line 95, in '
           'wrapper\n'
           '    return func(ctx, *args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 212, in run\n'
           '    loop.run_until_complete(run_func_check_upgrade(pipeline))\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 166, in '
           'run_func_check_upgrade\n'
           '    ret = await the_one_future\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 157, in run_pipeline_async\n'
           '    return await loop.run_in_executor(\n'
           '  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run\n'
           '    result = self.fn(*self.args, **self.kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 148, in '
           'run_pipeline_to_completion\n'
           '    raise e\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 134, in '
           'run_pipeline_to_completion\n'
           '    pipeline.run()\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 348, in run\n'
           '    for wu in itertools.islice(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/ingestion/source/openapi.py", line 225, in '
           'get_workunits\n'
           '    sw_dict = self.config.get_swagger()\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/ingestion/source/openapi.py", line 96, in '
           'get_swagger\n'
           '    sw_dict = get_swag_json(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/ingestion/source/openapi_parser.py", line 78, in '
           'get_swag_json\n'
           '    response = request_call(url=tot_url, username=username, password=password)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/datahub/ingestion/source/openapi_parser.py", line 56, in '
           'request_call\n'
           '    return requests.get(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/api.py", line 73, in get\n'
           '    return request("get", url, params=params, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/api.py", line 59, in request\n'
           '    return session.request(method=method, url=url, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/sessions.py", line 587, in request\n'
           '    resp = self.send(prep, **send_kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/sessions.py", line 723, in send\n'
           '    history = [resp for resp in gen]\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/sessions.py", line 723, in <listcomp>\n'
           '    history = [resp for resp in gen]\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects\n'
           '    resp = self.send(\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/sessions.py", line 701, in send\n'
           '    r = adapter.send(request, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-openapi-0.9.0/lib/python3.10/site-packages/requests/adapters.py", line 563, in send\n'
           '    raise SSLError(e, request=request)\n'
           "requests.exceptions.SSLError: HTTPSConnectionPool(host='*', port=443): Max retries exceeded "
           "with url: /docs/v2/swagger (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: "
           "self signed certificate in certificate chain (_ssl.c:997)')))\n"
           '[2022-11-01 17:17:15,852] ERROR    {datahub.entrypoints:195} - Command failed: \n'
           "\tHTTPSConnectionPool(host='**', port=443): Max retries exceeded with url: /docs/v2/swagger "
           "(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in "
           "certificate chain (_ssl.c:997)'))).\n"
           '\tRun with --debug to get full stacktrace.\n'
           "\te.g. 'datahub --debug ingest run -c /tmp/datahub/ingest/76c822f0-99dd-45d3-8937-11414b0e1072/recipe.yml --report-to "
           "/tmp/datahub/ingest/76c822f0-99dd-45d3-8937-11414b0e1072/ingestion_report.json'\n",
           "2022-11-01 17:17:17.441890 [exec_id=76c822f0-99dd-45d3-8937-11414b0e1072] INFO: Failed to execute 'datahub ingest'",
           '2022-11-01 17:17:17.442055 [exec_id=76c822f0-99dd-45d3-8937-11414b0e1072] INFO: Caught exception EXECUTING '
           'task_id=76c822f0-99dd-45d3-8937-11414b0e1072, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 123, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 227, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'structured_report': '{"source": {"type": "openapi", "report": {"events_produced": "0", "events_produced_per_sec": "0", "event_ids": [], '
                      '"warnings": {}, "failures": {}, "start_time": "2022-11-01 17:17:15.273730 (now).", "running_time": "0.14 seconds"}}, "sink": '
                      '{"type": "datahub-rest", "report": {"total_records_written": "0", "records_written_per_second": "0", "warnings": [], '
                      '"failures": [], "start_time": "2022-11-01 17:17:15.268643 (now).", "current_time": "2022-11-01 17:17:15.410341 (now).", '
                      '"total_duration_in_seconds": "0.14", "gms_version": "v0.9.0", "pending_requests": "0"}}}'}
Execution finished with errors.

**Comment by hsheth2** [comment] 2022-11-02 21:47
Based on the stack trace, it looks like the issue is in fetching the OpenAPI spec and not in the datahub-rest emitter (which sends metadata to datahub)

We're using the `requests` package under the hood to fetch the openapi spec. Could you check if the openapi spec host also has a self-signed cert in its chain?

**Comment by fgoiriz** [comment] 2022-11-14 15:07
If you need a workaround:
modify datahub/metadata-ingestion/src/datahub/emitter/rest_emitter.py
if it is installed in a venv it will probably be in venv/lib/python3.10/site-packages/datahub/emitter
or if in global env it will probably be in /home/youruser/.local/lib/python3.10/site-packages/datahub/emitter/rest_emitter.py

Modify line 65 
from: disable_ssl_verification: bool = False,
to: disable_ssl_verification: bool = True,

**Comment by zed-intelliflo** [comment] 2022-11-14 16:59
> If you need a workaround: modify datahub/metadata-ingestion/src/datahub/emitter/rest_emitter.py if it is installed in a venv it will probably be in venv/lib/python3.10/site-packages/datahub/emitter or if in global env it will probably be in /home/youruser/.local/lib/python3.10/site-packages/datahub/emitter/rest_emitter.py
> 
> Modify line 65 from: disable_ssl_verification: bool = False, to: disable_ssl_verification: bool = True,

Awesome. Will try that.

**Comment by laulpogan** [comment] 2022-12-07 19:57
Hi @zed-intelliflo   this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.

**Closed by laulpogan** 2022-12-07 19:57 UTC
Labels: bug
