### ISSUE TITLE
cannot  update the comments for existing column with ingestion

### ISSUE THREAD

**Issue by suishaojian** [datahub-project/datahub#4758] opened 2022-04-27 05:28 UTC
Hello,
When I import PostgreSQL metadata using ingestion tool, why can't I update the comments for existing column? It can be added, but not updated. 
I have not found the relevant configuration method, or whether there is already a similar issue. If there is, I hope anyone can provide it. Thank you so much. 

version: 0.8.33

Configure Recipe :
![image](https://user-images.githubusercontent.com/20984440/165446656-6e5c5f78-9b4a-4150-b7b0-c0e7f900c095.png)

**Comment by xiphl** [comment] 2022-04-27 06:10
"why can't I update the comments for existing column? It can be added, but not updated."
if you were to click on the "edit description" button for the field, does the updated description (from ingestion) show up at the bottom of the popup box?

**Comment by suishaojian** [comment] 2022-04-27 06:37
> "why can't I update the comments for existing column? It can be added, but not updated." if you were to click on the "edit description" button for the field, does the updated description (from ingestion) show up at the bottom of the popup box?

Aha，thanks for the warning. I do see a hint. But is there something wrong with the display? Why isn't the content of the second Edit displayed by default?

I edited from the webUI for the first time. Then , I edit from the navicat , Then I execute the ingestion.

![image](https://user-images.githubusercontent.com/20984440/165456353-804a5131-3ef2-4be6-a391-b41aababb984.png)

**Comment by suishaojian** [comment] 2022-04-29 01:29
> Hi, are you saying that you edited the description from the source and then reingested? And this is after you edited from the UI?

Yes. and I double check the data from msql as bellows:
![image](https://user-images.githubusercontent.com/20984440/165872132-1b9f75bc-26b5-4602-812a-efd3e78409a9.png)

As you can see , "edit from navicat..." is the last one version.

**Comment by swaroopjagadish** [comment] 2022-04-29 19:19
Closing this since this is expected behavior

**Closed by swaroopjagadish** 2022-04-29 19:19 UTC
