### ISSUE TITLE
Developing on Metadata Ingestion docs missing Cargo requirement

### ISSUE THREAD

**Issue by remisalmon** [datahub-project/datahub#5895] opened 2022-09-09 19:21 UTC
**Describe the bug**

The Developing on Metadata Ingestion docs at https://datahubproject.io/docs/metadata-ingestion/developing are missing Cargo as a requirement.

**To Reproduce**
1. Uninstall Cargo (if installed)
2. Run `gradlew :metadata-ingestion:installDev` (from https://datahubproject.io/docs/metadata-ingestion/developing#set-up-your-python-environment)
3. See error

```
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

> Task :metadata-ingestion:installDev FAILED

FAILURE: Build failed with an exception.
```

**Expected behavior**

Cargo should be listed as a requirement in https://datahubproject.io/docs/metadata-ingestion/developing#requirements

**Comment by hsheth2** [comment] 2022-12-06 23:31
I believe the root cause of this was https://github.com/delta-io/delta-rs/issues/972, which has now been fixed (although it hasn't been released yet)

I'm closing this for now, but @remisalmon let me know if this issue is still present in a week and we can re-open it.

**Closed by hsheth2** 2022-12-06 23:31 UTC
Labels: accepted, ingestion, docs
