### ISSUE TITLE
Quoted phrase search behaviour (v0-14-0-2)

### ISSUE THREAD

**Issue by mitchdawson1982** [datahub-project/datahub#11398] opened 2024-09-17 16:08 UTC
Hello, the DataHub demo instance's search appears to be broken. I am looking at [an example from the docs](https://datahubproject.io/docs/how/search/#advanced-queries):

> If you want to:
> 
> Exact match on term or phrase
> "datahub_schema" [Sample results](https://demo.datahubproject.io/search?%3Epage=1&query=%22datahub_schema%22)
> datahub_schema [Sample results](https://demo.datahubproject.io/search?page=1&query=datahub_schema)
> Enclosing one or more terms with double quotes will enforce exact matching on these terms, preventing further tokenization.

Firstly neither of the two links shown produce any results on the datahub demo instance any longer.

Since upgrading the quoted phrased search behaviour has changed significantly, please see the outputs below from the demo platform.

**Unquoted search on the demo platform:**
37 results returned including some with the phrase in the description.
![image](https://github.com/user-attachments/assets/0300db5f-4b01-486a-bfaf-c27d84e35a32)

### If I wanted to narrow it to entities containing this phrase.
Quoted phrased search on the demo platform:
No results were returned.
![image](https://github.com/user-attachments/assets/63573745-c96c-4e45-b385-ea1819c36c41)

### Quoted phrase matching the **entire** description value:
1 result returned
![image](https://github.com/user-attachments/assets/834a68dc-e9ac-4676-bd79-9ec12ede7b4f)

We note that quoted searches were [categorised](https://github.com/datahub-project/datahub/pull/10774) for exact matching, but surely we should not expect to enter the entire phrase to locate results. This doesn't appear consistent with previous phrase matching behaviour.

**Comment by david-leifker** [comment] 2024-09-20 17:21
1)
I think the key regression is a boolean flag where `prefix` matching is disabled on quoted search. What this means is that for certain fields [this](https://github.com/datahub-project/datahub/blob/master/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java#L405) code is not triggered. 

This is not a general phrase match however and is only a prefix phrase match. Your examples show this behavior where the phrase is at the start of the matched string. If the phrase was internal or at the end it would fail to match and this is the historical behavior for search.

2)
The only place that search has executes an actual phrase match is on certain fields that are designed to power autocomplete, indicated by the ngram analyzer on those fields. This doesn't cover the description however.

Solutions:

1) I will flip the flag in the search configuration since I believe it restores some of the expected behavior and doesn't negate the other functions in the referenced PR. This will be included in the next release.

2) The `search_config.yaml` can be overridden for `v0.14.x` and earlier versions which support search configuration in the same way.

3) Added test case and added a test to ensure that the default configuration and the test configuration doesn't deviate unexpectedly.

Ref: https://github.com/datahub-project/datahub/pull/11444

**Closed** 2024-09-20 19:58 UTC
Labels: bug

**Comment by david-leifker** [comment] 2024-09-21 21:16
2b) If using Helm the configuration can be overridden in the helm chart values in [this](https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/values.yaml#L505) section.
