### ISSUE TITLE
DataFetchingException Occurs when updateName via graphql

### ISSUE THREAD

**Issue by Cascol-SCUT** [datahub-project/datahub#5064] opened 2022-06-01 14:56 UTC
**Describe the bug**
DataFetchingException Occurs when updateName via graphql

**To Reproduce**
![1](https://user-images.githubusercontent.com/51443787/171434450-4cfc0f29-47cf-4dc1-a428-aa989fcf7ed9.png)
![2](https://user-images.githubusercontent.com/51443787/171434560-a2e36c15-0237-4b9a-b59a-3b327e4cbc56.png)

**Expected behavior**
Expect the name of dataset properly renamed.

**Comment by jjoyce0510** [comment] 2022-07-12 20:01
Hi @Cascol-SCUT - This is not a bug.

As documented in the GraphQL Docs here: https://datahubproject.io/docs/graphql/inputObjects#updateparentnodeinput

The **updateName** mutation is ONLY supported for entities of the following type:

- Glossary Nodes
- Glossary Terms

However, it is not supported for entities like Datasets, Dashboards, etc.

I've gone ahead and created a feature request for this functionality, so others can comment and upvote it publicly -> https://feature-requests.datahubproject.io/p/support-updatename-mutation-for-datasets

Closing the ticket for now.

Thanks
John

**Closed by jjoyce0510** 2022-07-12 20:01 UTC
Labels: bug, product
