### ISSUE TITLE
Unable to fetch metadata from dbt Cloud

### ISSUE THREAD

**Issue by hubertsl** [datahub-project/datahub#8567] opened 2023-08-03 18:47 UTC
**Describe the bug**
I installed datahub locally. After setting up the Ingestion for DBT Cloud through the UI and clicking "Save and Run", the run fails almost instantly with the following message

> ValueError: Unable to fetch metadata from dbt Cloud: [{'message': 'Error: This query exceeds the complexity limit. Consider breaking it up into separate queries or limiting to necessary fields. See the API docs for example queries and recommendations. The environment endpoint is recommended for most use cases to get the latest results for a dbt project.', 'extensions': {'code': 'COMPLEXITY_EXCEEDED'}}]

**To Reproduce**

**Expected behavior**
I would expect datahub to handle this exception and workaround the API - I can't see the API call made even in the debug view in the UI so can't give more direction.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 115.0.5790.110 

**Additional context**

**Comment by hsheth2** [comment] 2023-08-11 18:03
This was fixed in the latest CLI - could you try with cli version 0.10.5.4?

**Comment by wstolk** [comment] 2023-09-19 12:21
> This was fixed in the latest CLI - could you try with cli version 0.10.5.4?

I can confirm that this has been fixed in v0.11.0 of the CLI. Still doesn't work through the UI though. I'm not sure how Datahub works internally. Is there a reason why the CLI does work, but the UI still doesn't? And is there an ETA for a fix in the UI?

I would prefer to schedule my metadata ingestion in a unified way, so it would be preferred to have all connections setup in the same way.

**Comment by hsheth2** [comment] 2023-09-20 21:05
You can set the CLI version in the UI: https://datahubproject.io/docs/ui-ingestion/#advanced-running-with-a-specific-cli-version

I'm going to close this issue for now as it seems to be resolved.

**Closed by hsheth2** 2023-09-20 21:05 UTC
Labels: bug
