### ISSUE TITLE
Defect: Navigation to higher pages on catalog/search results in an error

### ISSUE THREAD

**Issue by samanthafigueredo5** [datahub-project/datahub#6720] opened 2022-12-09 15:13 UTC
**Describe the bug**
When traversing to higher page numbers client-side times out after ~30 seconds when it does not get a response back from the graphql query being made. 

**To Reproduce**
1. Go to My Data page without any search condition 
3. Traverse to pages higher than say 500 (if data allows)
4. Shows 503 timeout error

**Expected behavior**
Data should be able to come back. Seems the graphql query executes but from 0, significantly slowing queries beginning with higher indexes.
**Screenshots**
<img width="1012" alt="Screen Shot 2022-12-09 at 10 08 50 AM" src="https://user-images.githubusercontent.com/47129961/206733327-be0bad6b-f5bf-4769-ac11-c98dfa70af57.png">
<img width="1030" alt="Screen Shot 2022-12-09 at 10 09 04 AM" src="https://user-images.githubusercontent.com/47129961/206733330-b15b4d2a-d5eb-4131-a2fc-611e5dc35316.png">
<img width="1012" alt="Screen Shot 2022-12-09 at 10 09 13 AM" src="https://user-images.githubusercontent.com/47129961/206733332-b246b00a-07a8-42af-bd4e-3f7a6df369bd.png">

**Comment by andrunah** [comment] 2022-12-29 21:07
Hi. Thied the fix from PR and it does not seem to fully resolve the issue. Now there is `No results found for ""` message instead of 503...
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/17752048/210011171-b0cd170c-630e-4b5e-9681-87c4146d7c77.png">

**Comment by david-leifker** [comment] 2022-12-29 22:54
This is a problem with the way pagination is done for large indices in Elasticsearch. I've started the work to fix this however likely won't be ready until early Jan.

**Comment by jjoyce0510** [comment] 2023-01-03 16:18
^^ This is a high priority item for us

**Comment by aditya-radhakrishnan** [comment] 2023-01-24 05:19
I'm going to close this out as this is a duplicate of this issue https://github.com/datahub-project/datahub/issues/4575.

Please follow our updates there!

**Closed by aditya-radhakrishnan** 2023-01-24 05:19 UTC
Labels: bug, accepted, product, high-priority

**Comment by andrunah** [comment] 2023-01-24 05:26
@aditya-radhakrishnan this is not the same issue. It happens even with smaller number of datasets, less than 5000
