### ISSUE TITLE
Transforms are not applied to the generated metadata events from profiling

### ISSUE THREAD

**Issue by sgomezvillamor** [datahub-project/datahub#3300] opened 2021-09-27 13:41 UTC
**Describe the bug**

Transforms applied to an event are not applied to the events from the profiling stage.

**To Reproduce**

We have some custom transform that applies some update on the URN of the entity. In this case, some enrichment on the `dataPlatform`:

```
transformers:
  - type: "adevinta_datahub_transforms.add_custom_dataplatform.AddCustomDataplatform"
    config: 
      dataPlatform: "redshift@xxxxx"
```

This is the event generated for the entity (note the URN: `'urn:li:dataset:(urn:li:dataPlatform:redshift@xxxxx,dwh_sch.dm.cognition_metrics,PROD)`):

```
RecordEnvelope(record=MetadataChangeEventClass({'auditHeader': None, 'proposedSnapshot': DatasetSnapshotClass({'urn': 'urn:li:dataset:(urn:li:dataPlatform:redshift@xxxxx,dwh_sch.dm.cognition_metrics,PROD)', ...., metadata={'workunit_id': 'dwh_sch.dm.cognition_metrics'})
```

whereas this is the event generated for the profiling stage (note the URN: `urn:li:dataset:(urn:li:dataPlatform:redshift,dwh_sch.dm.cognition_metrics,PROD)` where the URN misses the transform):

```
RecordEnvelope(record=MetadataChangeProposalWrapper(entityType='dataset', changeType='UPSERT', entityUrn='urn:li:dataset:(urn:li:dataPlatform:redshift,dwh_sch.dm.cognition_metrics,PROD)', entityKeyAspect=None, auditHeader=None, aspectName='datasetProfile', ...., metadata={'workunit_id': 'profile-dwh_sch.dm.cognition_metrics'})
````

This results in duplicated entities: one with the correct `dataPlatform` and another one with the incorrect one.

The same issue happens with other simple transforms such as `simple_add_dataset_ownership`. The event from the profiling  stage misses the additional owners. In this case, maybe this was not noted before because as soon as both the initial event and the one from the profiling stage have the same URN, everything is fine. However, as soon as one of them diverges, all differences are noted.

**Expected behavior**

All transforms applied to the initial event are also applied to the event resulting from the profiling stage.

Maybe, the problem is this decoupling and a single event including the profiling when enabled is the way to avoid these events being out of sync.

**Additional context**

This is running v 0.8.12.

**Comment by claudio-benfatto** [comment] 2021-10-04 07:51
Hi @sgomezvillamor, I was having a look at this to better understand what is happening and to try to fix this _bug_ if possible.
I now believe that the unexpected behaviour is (mostly) due to the fact that we are bending the rules by modifying the `urn` of an event.

There is ofc also a more technical explanation to why this happens, and it is that the event generated by the profiling is not of type `MetadataChangeEventClass` but of type `MetadataChangeProposalWrapper` (I learned [here](https://datahubproject.io/docs/advanced/mcp-mcl/) the rationale behind this distinction).

In our transformer, this method:
```
    def transform(
        self, record_envelopes: Iterable[RecordEnvelope]
    ) -> Iterable[RecordEnvelope]:

        # loop over envelopes
        for envelope in record_envelopes:
            if isinstance(envelope.record, MetadataChangeEventClass):
                envelope.record = self.transform_one(envelope.record)
            yield envelope
  ```
  by the means of this line:
  ```if isinstance(envelope.record, MetadataChangeEventClass)```
  we are explicitly skipping those event types for the transformation (btw a similar behaviour affects the other transformers as well, but I'm not sure if it could create potential problems, especially in the cases when the aspect we are changing is the one affected by the transformation. Could it have resulted in a bug if the transformation was mutating the `DatasetProfile` aspect for example?).
  
 To be honest, in this case, I don't think this is either a problem for `simple_add_dataset_ownership`, because the `MetadataChangeProposal` is encapsulating a single aspect (to reinforce the concept of an aspect as an atomic write domain I believe). So it simply shouldn't affect the original entity neither be relevant for this transformation.
 
 I hope this can help clarify the issue :)

**Comment by claudio-benfatto** [comment] 2021-10-04 10:13
> If I have understood correctly, you mean we could fix by additionally including `MetadataChangeProposalWrapper` in the loop of events in our transform. Is that?

correct, `MetadataChangeProposalWrapper` and `MetadataChangeProposal`. However the field is called differently in there and they do not form part of the same object hierarchy (read as: we need to treat the `MetadataChangeEvent` and `MetadataChangeProposal` differently)
 
> Since modifying the URN may be the root cause of all this and if there are good reasons to forbid changes in the URN, is this something that could or should be prevented in the transforms?

This is surely an interesting question. I also wonder if having two different and unrelated kinds of events (`MetadataChangeEvent` and `MetadataChangeProposal`) could also be a source of potential bugs for more straightforward transformations that want to modify those aspects when the ingestors mix the two.

**Comment by sgomezvillamor** [comment] 2021-10-14 07:06
@shirshanka that sounds great! Thanks for the heads up.

**Comment by shirshanka** [comment] 2022-05-05 22:32
Closing as this has been fixed.

**Closed by shirshanka** 2022-05-05 22:32 UTC
Labels: bug, accepted
