### ISSUE TITLE
quickstart cannot running three containers

### ISSUE THREAD

**Issue by Peryy** [datahub-project/datahub#8312] opened 2023-06-27 02:42 UTC
**Describe the bug**
No errors but three containers cannot running and keep creating
![Image_20230627103943](https://github.com/datahub-project/datahub/assets/59139729/ec90a80f-054f-4680-a249-86a44b03ab2d)

**Desktop (please complete the following information):**
My datahub version 
DataHub CLI version: 0.10.4.2
Python version: 3.8.12 (default, Jun 26 2023, 15:09:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

**Comment by hsheth2** [comment] 2023-07-11 00:24
@Peryy I believe this is a duplicate of https://github.com/datahub-project/datahub/issues/8133

Could you try with a slightly more recent cli version, and don't specify the --docker-compose file manually (we'll automatically download it)

**Closed by hsheth2** 2023-07-11 00:24 UTC
Labels: bug

**Comment by leandro-ferreira-farm** [comment] 2023-07-14 01:31
Have the same trouble here. I cannot up docker broker. 


![image](https://github.com/datahub-project/datahub/assets/127340510/e54d7126-13c7-41c0-b758-7c16f7ba771d)
